# Create report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "price": 1000,
    "make": "Toyota",
    "model": "Camry",
    "year": 2020,
    "mileage": 10000,
    "lat": 40.7128,
    "lng": -74.0060
}

# Approve an existing report
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved": true
}


# Get an estimate of existing vehicle
GET http://localhost:3000/reports?make=Toyota&model=Camry&year=2020&mileage=10000&lat=40.7128&lng=-74.0060
